name: Docker CI/CD Pipeline

on:
  workflow_dispatch:

  push:
    branches:
      - main

############################################################
# Global Variables
############################################################

env:
  AWS_REGION: ap-south-1
  ACCOUNT_ID: 464505731561
  ECR_REPOSITORY: actions-demo

############################################################
# Jobs
############################################################

jobs:

############################################################
# BUILD
############################################################

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

############################################################
# UNIT TEST
############################################################

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - name: Run Unit Tests
        run: |
          echo "All tests passed"

############################################################
# LINT
############################################################

  lint:
    name: Lint
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - name: Run Lint
        run: |
          echo "Lint successful"

############################################################
# DOCKER BUILD & PUSH
############################################################

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    needs:
      - unit-test
      - lint

    outputs:
      image_uri: ${{ steps.image.outputs.image_uri }}

    steps:

      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Generate Image URI
        id: image
        run: |
          IMAGE_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${GITHUB_SHA}

          echo "Image URI: $IMAGE_URI"

          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        run: |
      
          docker build \
            -t ${{ steps.image.outputs.image_uri }} \
            -t ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:latest \
            .

      - name: Push Docker Images
        run: |
      
          docker push ${{ steps.image.outputs.image_uri }}
      
          docker push ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:latest


############################################################
# DEPLOY
############################################################

  deploy:

    name: Deploy to EKS
  
    runs-on: ubuntu-latest
  
    needs: docker
  
    steps:
  
      - uses: actions/checkout@v4
  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
  
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
  
      - name: Configure kubectl
        run: |
  
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name eks-lab-dev
  
      - name: Deploy Application
        run: |
  
          kubectl apply -f k8s/

      - name: Restart Deployment
        run: |
          kubectl rollout restart deployment/devops-demo \
            -n devops-demo
      
      - name: Wait for Rollout
        run: |
          kubectl rollout status deployment/devops-demo \
            -n devops-demo
  