name: Build Matrix Workflow

on:
  workflow_dispatch:
    inputs:
      runner-type:
        description: 'Select the type of runner to use for the build'
        required: true
        type: choice
        default: 'ubuntu-latest'
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest

jobs:
  job1:
    runs-on: ${{ github.event.inputs.runner-type }}

    strategy:
      matrix:
        version: [22, 24]
    
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Display Node.js Version
        run: node -v